### ISSUE TITLE
Calling c++ code from python using pybind11 creates an error when creating Spacy::Spacy object on stack but not as a pointer

### ISSUE THREAD

**Issue by nuttyartist** [d99kris/spacy-cpp#20]
Here's a minimal example to reproduce this error:

[cmake-add-subdirectory-hdr.zip](https://github.com/d99kris/spacy-cpp/files/10840893/cmake-add-subdirectory-hdr.zip)

To reproduce this

```
cd build
cmake .. && make
cd ../src/
python pyTest.py 
```

Why does the following code (creating Spacy::Spacy object on stack) creates an error:

```c++
  Spacy::Spacy spacy;
  auto nlp = spacy.load("en_core_web_sm");
```

```
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: finalizing (tstate=0x00000001029b63c8)

Abort trap: 6
```

But this one works?

```c++
  Spacy::Spacy* spacy = new Spacy::Spacy();
  auto nlp = spacy->load("en_core_web_sm");
```

**Comment by d99kris** [comment]
Hi! Spacy-cpp is a C++ wrapper library for the (Python) spacy library, so internally it sets up a Python interpreter instance which is used to perform the various spacy calls. Spacy-cpp is not intended to be called from Python, and googling above error message shows some other people encountering similar problem when calling Python -> C++ -> Python due to the GIL (Python's global interpreter lock). 

Having that said, I suspect the reason it works with the heap object is that the code does `new Spacy..` without corresponding `delete`, thus the object is not cleaned up. With the stack object it's guaranteed to be cleaned up at the end of it's scope.

Supporting usage from Python/pybind11 is probably outside the scope of `spacy-cpp`, but I'm curious what is the use-case, why not call spacy directly from Python (and not use C++ / spacy-cpp)?

**Edit**: A potential work-around/hack could be to comment out the call to `Py_Finalize()` from `Python::~Python()` in src/spacy/python.cpp - I've not tested this, it's just a guess.

**Comment by nuttyartist** [comment]
> Edit: A potential work-around/hack could be to comment out the call to Py_Finalize() from Python::~Python() in src/spacy/python.cpp - I've not tested this, it's just a guess.

Your guess was right. I'm unsure if I should keep it as a pointer as before with `src/spacy/python.cpp` unchanged or with this change. At the end of the day, I'm passing Python the flag to take ownership of the lifetime of the variables (via `py::return_value_policy::take_ownership`).

> but I'm curious what is the use-case, why not call spacy directly from Python (and not use C++ / spacy-cpp)?

Haha good question. I'm developing an app that given two words, finds related words that rhyme (spacy is used to identify pos tags). The server is very slow with pure Python, so I had to create a C++ binding using pybind11. But it resulted in a large overhead in transferring large data sets from C++ to Python. My solution is to score the rhyme couples in C++ and only return the top N rather than returning all the rhyme couples and scoring them in Python (just the data transfer will take a few seconds).

**Comment by d99kris** [comment]
> I'm unsure if I should keep it as a pointer as before with src/spacy/python.cpp unchanged or with this change. 

Generally, I would leave the third-party library (spacy-cpp) untouched to facilitate future potential updates of the library.

Thanks for sharing the background 🙂 

I will proceed to close this issue, as I believe a fix for this would be out of scope for spacy-cpp. Feel free to re-open if you have concerns. Thanks!
